apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sre-cw-host.serviceAccountName" . }}-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "sre-cw-host.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: admin-role
  apiGroup: rbac.authorization.k8s.io