apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sre-cw-host.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sre-cw-host.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sre-cw-host.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sre-cw-host.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sre-cw-host.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: "/data"
              name: host-data
            - mountPath: "/data/__tenant-data/sre-tenant-unique-efs-dynamic-sc-1"
              name: tenant-data-1
          command: [ "/bin/sh" ]
          # Replace "host" with "sleep" to guarantee pod starts
          # and can be SSHd into.
          args: [ "--", "/app/cw-run.sh", "host" ]
          env:
          - name: ATHENA_HOST_RUN_FILE
            value: /data/__host-data/run.yaml
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - name: host-data
          persistentVolumeClaim:
            claimName: {{ (index .Values.persistentVolumeClaims 0).name }}
        - name: tenant-data-1
          persistentVolumeClaim:
            claimName: {{ (index .Values.persistentVolumeClaims 1).name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
