apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-cw-host.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sre-cw-host.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
      {{- include "sre-cw-host.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP

