{{- if .Values.storageClass.create -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: storage.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: storage.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
{{- with .Values.storageClass }}
kind: StorageClass
metadata:
  name: {{ .name }}
provisioner: efs.csi.aws.com
{{- with .parameters }}
parameters:
{{ toYaml . | indent 2 }}
{{- end }}
---
{{- end }}
{{- end }}