name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone repo
      run: |
        "C:\Program Files\git\bin\git" clone https://github.com/yourusername/yourrepository.git C:\Test
