name: Run PowerShell Script

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  run-script:
    runs-on: windows-latest  # You can specify 'runs-on: self-hosted' if using a self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run PowerShell Script
        shell: pwsh
        run: C:\Test\hello.ps1
