name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy code to target directory
      run: |
        mkdir "C:\Test3"
        xcopy /E /I . "C:\Test3"
